language: emacs-lisp

script:
  - emacs --version
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-26.1-travis-travis-linux-xenial
    - EVM_EMACS=emacs-25.3-travis
    # don't need 25.2 because it's the same 25.3
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-24.4-travis
    # - EVM_EMACS=emacs-git-snapshot-travis
# matrix:
#   fast_finish: true
#   # allow_failures:
#   #   - env: EVM_EMACS=emacs-git-snapshot-travis

sudo: no
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask

# notifications:
#   email: false
